name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- DEPLOY ADMIN UI ---
      - name: Deploy Admin UI
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_ADMIN_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/moe_admin_ui"
          output_location: "dist"
        env: # Truyền biến cho Admin UI
          VITE_ADMIN_URL: ${{ secrets.VITE_ADMIN_URL }}

      # --- DEPLOY STUDENT UI ---
      - name: Deploy Student UI
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_STUDENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/moe_student_ui"
          output_location: "dist"
        env: # Truyền biến cho Student UI
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_SERVICE_URL: ${{ secrets.VITE_SERVICE_URL }}